chore(deps): update multiple deps
NerdWalletOSS/shepherd pull request #604
Opened 2023-09-10 19:46 UTC by kavitha186

2023-09-10 20:53 UTC, aorinevo requested changes

2023-09-10 20:53 UTC, aorinevo commented on package-lock.json
No need to commit package-lock since we have yarn.lock.

2023-09-10 21:41 UTC, kavitha186 commented on package-lock.json
yes fixed

2023-09-10 22:22 UTC, aorinevo approved these changes

2023-09-10 22:32 UTC, aorinevo commented
We can drop support for Node v12 and v14.

2023-09-11 13:14 UTC, aorinevo commented
Opened a separate PR to update CI and Release workflows (see https://github.com/NerdWalletOSS/shepherd/pull/605 )

2023-09-11 18:29 UTC, aorinevo commented
Closing this in favor of https://github.com/NerdWalletOSS/shepherd/pull/605 

The dependency management was non-trivial and required some review subtle changes when upgrading multiple packages.

2023-09-11 18:30 UTC, closed without merging